package com.sample.gradle.springbatch.common.entity;

import java.io.Serializable;
import java.util.Date;

public class HUserInfo extends HUserInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.user_disp_name
	 * @mbg.generated
	 */
	private String userDispName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.kanji_family_name
	 * @mbg.generated
	 */
	private String kanjiFamilyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.kanji_first_name
	 * @mbg.generated
	 */
	private String kanjiFirstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.kana_family_name
	 * @mbg.generated
	 */
	private String kanaFamilyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.kana_first_name
	 * @mbg.generated
	 */
	private String kanaFirstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.mail_address
	 * @mbg.generated
	 */
	private String mailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.postal_code
	 * @mbg.generated
	 */
	private String postalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.address
	 * @mbg.generated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.address_romaji
	 * @mbg.generated
	 */
	private String addressRomaji;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.birth_date
	 * @mbg.generated
	 */
	private String birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.age
	 * @mbg.generated
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.sex
	 * @mbg.generated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.phone_number
	 * @mbg.generated
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.cellphone_number
	 * @mbg.generated
	 */
	private String cellphoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.fax_number
	 * @mbg.generated
	 */
	private String faxNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_reg_user_mng_number
	 * @mbg.generated
	 */
	private String historyRegUserMngNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_reg_date
	 * @mbg.generated
	 */
	private Date historyRegDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_reg_func_ID
	 * @mbg.generated
	 */
	private String historyRegFuncId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_update_user_mng_number
	 * @mbg.generated
	 */
	private String historyUpdateUserMngNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_update_date
	 * @mbg.generated
	 */
	private Date historyUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.history_update_func_ID
	 * @mbg.generated
	 */
	private String historyUpdateFuncId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.reg_user_mng_number
	 * @mbg.generated
	 */
	private String regUserMngNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.reg_date
	 * @mbg.generated
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.reg_func_ID
	 * @mbg.generated
	 */
	private String regFuncId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.update_user_mng_number
	 * @mbg.generated
	 */
	private String updateUserMngNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.update_date
	 * @mbg.generated
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column h_user_info.update_func_ID
	 * @mbg.generated
	 */
	private String updateFuncId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.user_id
	 * @return  the value of h_user_info.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.user_id
	 * @param userId  the value for h_user_info.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.password
	 * @return  the value of h_user_info.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.password
	 * @param password  the value for h_user_info.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.user_disp_name
	 * @return  the value of h_user_info.user_disp_name
	 * @mbg.generated
	 */
	public String getUserDispName() {
		return userDispName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.user_disp_name
	 * @param userDispName  the value for h_user_info.user_disp_name
	 * @mbg.generated
	 */
	public void setUserDispName(String userDispName) {
		this.userDispName = userDispName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.kanji_family_name
	 * @return  the value of h_user_info.kanji_family_name
	 * @mbg.generated
	 */
	public String getKanjiFamilyName() {
		return kanjiFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.kanji_family_name
	 * @param kanjiFamilyName  the value for h_user_info.kanji_family_name
	 * @mbg.generated
	 */
	public void setKanjiFamilyName(String kanjiFamilyName) {
		this.kanjiFamilyName = kanjiFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.kanji_first_name
	 * @return  the value of h_user_info.kanji_first_name
	 * @mbg.generated
	 */
	public String getKanjiFirstName() {
		return kanjiFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.kanji_first_name
	 * @param kanjiFirstName  the value for h_user_info.kanji_first_name
	 * @mbg.generated
	 */
	public void setKanjiFirstName(String kanjiFirstName) {
		this.kanjiFirstName = kanjiFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.kana_family_name
	 * @return  the value of h_user_info.kana_family_name
	 * @mbg.generated
	 */
	public String getKanaFamilyName() {
		return kanaFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.kana_family_name
	 * @param kanaFamilyName  the value for h_user_info.kana_family_name
	 * @mbg.generated
	 */
	public void setKanaFamilyName(String kanaFamilyName) {
		this.kanaFamilyName = kanaFamilyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.kana_first_name
	 * @return  the value of h_user_info.kana_first_name
	 * @mbg.generated
	 */
	public String getKanaFirstName() {
		return kanaFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.kana_first_name
	 * @param kanaFirstName  the value for h_user_info.kana_first_name
	 * @mbg.generated
	 */
	public void setKanaFirstName(String kanaFirstName) {
		this.kanaFirstName = kanaFirstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.mail_address
	 * @return  the value of h_user_info.mail_address
	 * @mbg.generated
	 */
	public String getMailAddress() {
		return mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.mail_address
	 * @param mailAddress  the value for h_user_info.mail_address
	 * @mbg.generated
	 */
	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.postal_code
	 * @return  the value of h_user_info.postal_code
	 * @mbg.generated
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.postal_code
	 * @param postalCode  the value for h_user_info.postal_code
	 * @mbg.generated
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.address
	 * @return  the value of h_user_info.address
	 * @mbg.generated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.address
	 * @param address  the value for h_user_info.address
	 * @mbg.generated
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.address_romaji
	 * @return  the value of h_user_info.address_romaji
	 * @mbg.generated
	 */
	public String getAddressRomaji() {
		return addressRomaji;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.address_romaji
	 * @param addressRomaji  the value for h_user_info.address_romaji
	 * @mbg.generated
	 */
	public void setAddressRomaji(String addressRomaji) {
		this.addressRomaji = addressRomaji;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.birth_date
	 * @return  the value of h_user_info.birth_date
	 * @mbg.generated
	 */
	public String getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.birth_date
	 * @param birthDate  the value for h_user_info.birth_date
	 * @mbg.generated
	 */
	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.age
	 * @return  the value of h_user_info.age
	 * @mbg.generated
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.age
	 * @param age  the value for h_user_info.age
	 * @mbg.generated
	 */
	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.sex
	 * @return  the value of h_user_info.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.sex
	 * @param sex  the value for h_user_info.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.phone_number
	 * @return  the value of h_user_info.phone_number
	 * @mbg.generated
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.phone_number
	 * @param phoneNumber  the value for h_user_info.phone_number
	 * @mbg.generated
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.cellphone_number
	 * @return  the value of h_user_info.cellphone_number
	 * @mbg.generated
	 */
	public String getCellphoneNumber() {
		return cellphoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.cellphone_number
	 * @param cellphoneNumber  the value for h_user_info.cellphone_number
	 * @mbg.generated
	 */
	public void setCellphoneNumber(String cellphoneNumber) {
		this.cellphoneNumber = cellphoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.fax_number
	 * @return  the value of h_user_info.fax_number
	 * @mbg.generated
	 */
	public String getFaxNumber() {
		return faxNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.fax_number
	 * @param faxNumber  the value for h_user_info.fax_number
	 * @mbg.generated
	 */
	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_reg_user_mng_number
	 * @return  the value of h_user_info.history_reg_user_mng_number
	 * @mbg.generated
	 */
	public String getHistoryRegUserMngNumber() {
		return historyRegUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_reg_user_mng_number
	 * @param historyRegUserMngNumber  the value for h_user_info.history_reg_user_mng_number
	 * @mbg.generated
	 */
	public void setHistoryRegUserMngNumber(String historyRegUserMngNumber) {
		this.historyRegUserMngNumber = historyRegUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_reg_date
	 * @return  the value of h_user_info.history_reg_date
	 * @mbg.generated
	 */
	public Date getHistoryRegDate() {
		return historyRegDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_reg_date
	 * @param historyRegDate  the value for h_user_info.history_reg_date
	 * @mbg.generated
	 */
	public void setHistoryRegDate(Date historyRegDate) {
		this.historyRegDate = historyRegDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_reg_func_ID
	 * @return  the value of h_user_info.history_reg_func_ID
	 * @mbg.generated
	 */
	public String getHistoryRegFuncId() {
		return historyRegFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_reg_func_ID
	 * @param historyRegFuncId  the value for h_user_info.history_reg_func_ID
	 * @mbg.generated
	 */
	public void setHistoryRegFuncId(String historyRegFuncId) {
		this.historyRegFuncId = historyRegFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_update_user_mng_number
	 * @return  the value of h_user_info.history_update_user_mng_number
	 * @mbg.generated
	 */
	public String getHistoryUpdateUserMngNumber() {
		return historyUpdateUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_update_user_mng_number
	 * @param historyUpdateUserMngNumber  the value for h_user_info.history_update_user_mng_number
	 * @mbg.generated
	 */
	public void setHistoryUpdateUserMngNumber(String historyUpdateUserMngNumber) {
		this.historyUpdateUserMngNumber = historyUpdateUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_update_date
	 * @return  the value of h_user_info.history_update_date
	 * @mbg.generated
	 */
	public Date getHistoryUpdateDate() {
		return historyUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_update_date
	 * @param historyUpdateDate  the value for h_user_info.history_update_date
	 * @mbg.generated
	 */
	public void setHistoryUpdateDate(Date historyUpdateDate) {
		this.historyUpdateDate = historyUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.history_update_func_ID
	 * @return  the value of h_user_info.history_update_func_ID
	 * @mbg.generated
	 */
	public String getHistoryUpdateFuncId() {
		return historyUpdateFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.history_update_func_ID
	 * @param historyUpdateFuncId  the value for h_user_info.history_update_func_ID
	 * @mbg.generated
	 */
	public void setHistoryUpdateFuncId(String historyUpdateFuncId) {
		this.historyUpdateFuncId = historyUpdateFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.reg_user_mng_number
	 * @return  the value of h_user_info.reg_user_mng_number
	 * @mbg.generated
	 */
	public String getRegUserMngNumber() {
		return regUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.reg_user_mng_number
	 * @param regUserMngNumber  the value for h_user_info.reg_user_mng_number
	 * @mbg.generated
	 */
	public void setRegUserMngNumber(String regUserMngNumber) {
		this.regUserMngNumber = regUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.reg_date
	 * @return  the value of h_user_info.reg_date
	 * @mbg.generated
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.reg_date
	 * @param regDate  the value for h_user_info.reg_date
	 * @mbg.generated
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.reg_func_ID
	 * @return  the value of h_user_info.reg_func_ID
	 * @mbg.generated
	 */
	public String getRegFuncId() {
		return regFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.reg_func_ID
	 * @param regFuncId  the value for h_user_info.reg_func_ID
	 * @mbg.generated
	 */
	public void setRegFuncId(String regFuncId) {
		this.regFuncId = regFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.update_user_mng_number
	 * @return  the value of h_user_info.update_user_mng_number
	 * @mbg.generated
	 */
	public String getUpdateUserMngNumber() {
		return updateUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.update_user_mng_number
	 * @param updateUserMngNumber  the value for h_user_info.update_user_mng_number
	 * @mbg.generated
	 */
	public void setUpdateUserMngNumber(String updateUserMngNumber) {
		this.updateUserMngNumber = updateUserMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.update_date
	 * @return  the value of h_user_info.update_date
	 * @mbg.generated
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.update_date
	 * @param updateDate  the value for h_user_info.update_date
	 * @mbg.generated
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column h_user_info.update_func_ID
	 * @return  the value of h_user_info.update_func_ID
	 * @mbg.generated
	 */
	public String getUpdateFuncId() {
		return updateFuncId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column h_user_info.update_func_ID
	 * @param updateFuncId  the value for h_user_info.update_func_ID
	 * @mbg.generated
	 */
	public void setUpdateFuncId(String updateFuncId) {
		this.updateFuncId = updateFuncId;
	}
}