package com.sample.gradle.springbatch.common.entity;

import java.io.Serializable;

public class TUserInfoKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.user_mng_number
	 * @mbg.generated
	 */
	private String userMngNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.user_mng_number
	 * @return  the value of t_user_info.user_mng_number
	 * @mbg.generated
	 */
	public String getUserMngNumber() {
		return userMngNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.user_mng_number
	 * @param userMngNumber  the value for t_user_info.user_mng_number
	 * @mbg.generated
	 */
	public void setUserMngNumber(String userMngNumber) {
		this.userMngNumber = userMngNumber;
	}
}