package com.sample.gradle.springbatch.common.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TUserInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public TUserInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserMngNumberIsNull() {
			addCriterion("user_mng_number is null");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberIsNotNull() {
			addCriterion("user_mng_number is not null");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberEqualTo(String value) {
			addCriterion("user_mng_number =", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberNotEqualTo(String value) {
			addCriterion("user_mng_number <>", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberGreaterThan(String value) {
			addCriterion("user_mng_number >", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberGreaterThanOrEqualTo(String value) {
			addCriterion("user_mng_number >=", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberLessThan(String value) {
			addCriterion("user_mng_number <", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberLessThanOrEqualTo(String value) {
			addCriterion("user_mng_number <=", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberLike(String value) {
			addCriterion("user_mng_number like", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberNotLike(String value) {
			addCriterion("user_mng_number not like", value, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberIn(List<String> values) {
			addCriterion("user_mng_number in", values, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberNotIn(List<String> values) {
			addCriterion("user_mng_number not in", values, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberBetween(String value1, String value2) {
			addCriterion("user_mng_number between", value1, value2, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andUserMngNumberNotBetween(String value1, String value2) {
			addCriterion("user_mng_number not between", value1, value2, "userMngNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIsNull() {
			addCriterion("revision_number is null");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIsNotNull() {
			addCriterion("revision_number is not null");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberEqualTo(Integer value) {
			addCriterion("revision_number =", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotEqualTo(Integer value) {
			addCriterion("revision_number <>", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberGreaterThan(Integer value) {
			addCriterion("revision_number >", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("revision_number >=", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberLessThan(Integer value) {
			addCriterion("revision_number <", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberLessThanOrEqualTo(Integer value) {
			addCriterion("revision_number <=", value, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberIn(List<Integer> values) {
			addCriterion("revision_number in", values, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotIn(List<Integer> values) {
			addCriterion("revision_number not in", values, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberBetween(Integer value1, Integer value2) {
			addCriterion("revision_number between", value1, value2, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andRevisionNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("revision_number not between", value1, value2, "revisionNumber");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andUserDispNameIsNull() {
			addCriterion("user_disp_name is null");
			return (Criteria) this;
		}

		public Criteria andUserDispNameIsNotNull() {
			addCriterion("user_disp_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserDispNameEqualTo(String value) {
			addCriterion("user_disp_name =", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameNotEqualTo(String value) {
			addCriterion("user_disp_name <>", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameGreaterThan(String value) {
			addCriterion("user_disp_name >", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_disp_name >=", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameLessThan(String value) {
			addCriterion("user_disp_name <", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameLessThanOrEqualTo(String value) {
			addCriterion("user_disp_name <=", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameLike(String value) {
			addCriterion("user_disp_name like", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameNotLike(String value) {
			addCriterion("user_disp_name not like", value, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameIn(List<String> values) {
			addCriterion("user_disp_name in", values, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameNotIn(List<String> values) {
			addCriterion("user_disp_name not in", values, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameBetween(String value1, String value2) {
			addCriterion("user_disp_name between", value1, value2, "userDispName");
			return (Criteria) this;
		}

		public Criteria andUserDispNameNotBetween(String value1, String value2) {
			addCriterion("user_disp_name not between", value1, value2, "userDispName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameIsNull() {
			addCriterion("kanji_family_name is null");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameIsNotNull() {
			addCriterion("kanji_family_name is not null");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameEqualTo(String value) {
			addCriterion("kanji_family_name =", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameNotEqualTo(String value) {
			addCriterion("kanji_family_name <>", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameGreaterThan(String value) {
			addCriterion("kanji_family_name >", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("kanji_family_name >=", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameLessThan(String value) {
			addCriterion("kanji_family_name <", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("kanji_family_name <=", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameLike(String value) {
			addCriterion("kanji_family_name like", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameNotLike(String value) {
			addCriterion("kanji_family_name not like", value, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameIn(List<String> values) {
			addCriterion("kanji_family_name in", values, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameNotIn(List<String> values) {
			addCriterion("kanji_family_name not in", values, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameBetween(String value1, String value2) {
			addCriterion("kanji_family_name between", value1, value2, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFamilyNameNotBetween(String value1, String value2) {
			addCriterion("kanji_family_name not between", value1, value2, "kanjiFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameIsNull() {
			addCriterion("kanji_first_name is null");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameIsNotNull() {
			addCriterion("kanji_first_name is not null");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameEqualTo(String value) {
			addCriterion("kanji_first_name =", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameNotEqualTo(String value) {
			addCriterion("kanji_first_name <>", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameGreaterThan(String value) {
			addCriterion("kanji_first_name >", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("kanji_first_name >=", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameLessThan(String value) {
			addCriterion("kanji_first_name <", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameLessThanOrEqualTo(String value) {
			addCriterion("kanji_first_name <=", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameLike(String value) {
			addCriterion("kanji_first_name like", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameNotLike(String value) {
			addCriterion("kanji_first_name not like", value, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameIn(List<String> values) {
			addCriterion("kanji_first_name in", values, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameNotIn(List<String> values) {
			addCriterion("kanji_first_name not in", values, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameBetween(String value1, String value2) {
			addCriterion("kanji_first_name between", value1, value2, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanjiFirstNameNotBetween(String value1, String value2) {
			addCriterion("kanji_first_name not between", value1, value2, "kanjiFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameIsNull() {
			addCriterion("kana_family_name is null");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameIsNotNull() {
			addCriterion("kana_family_name is not null");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameEqualTo(String value) {
			addCriterion("kana_family_name =", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameNotEqualTo(String value) {
			addCriterion("kana_family_name <>", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameGreaterThan(String value) {
			addCriterion("kana_family_name >", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameGreaterThanOrEqualTo(String value) {
			addCriterion("kana_family_name >=", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameLessThan(String value) {
			addCriterion("kana_family_name <", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameLessThanOrEqualTo(String value) {
			addCriterion("kana_family_name <=", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameLike(String value) {
			addCriterion("kana_family_name like", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameNotLike(String value) {
			addCriterion("kana_family_name not like", value, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameIn(List<String> values) {
			addCriterion("kana_family_name in", values, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameNotIn(List<String> values) {
			addCriterion("kana_family_name not in", values, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameBetween(String value1, String value2) {
			addCriterion("kana_family_name between", value1, value2, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFamilyNameNotBetween(String value1, String value2) {
			addCriterion("kana_family_name not between", value1, value2, "kanaFamilyName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameIsNull() {
			addCriterion("kana_first_name is null");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameIsNotNull() {
			addCriterion("kana_first_name is not null");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameEqualTo(String value) {
			addCriterion("kana_first_name =", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameNotEqualTo(String value) {
			addCriterion("kana_first_name <>", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameGreaterThan(String value) {
			addCriterion("kana_first_name >", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("kana_first_name >=", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameLessThan(String value) {
			addCriterion("kana_first_name <", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameLessThanOrEqualTo(String value) {
			addCriterion("kana_first_name <=", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameLike(String value) {
			addCriterion("kana_first_name like", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameNotLike(String value) {
			addCriterion("kana_first_name not like", value, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameIn(List<String> values) {
			addCriterion("kana_first_name in", values, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameNotIn(List<String> values) {
			addCriterion("kana_first_name not in", values, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameBetween(String value1, String value2) {
			addCriterion("kana_first_name between", value1, value2, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andKanaFirstNameNotBetween(String value1, String value2) {
			addCriterion("kana_first_name not between", value1, value2, "kanaFirstName");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNull() {
			addCriterion("mail_address is null");
			return (Criteria) this;
		}

		public Criteria andMailAddressIsNotNull() {
			addCriterion("mail_address is not null");
			return (Criteria) this;
		}

		public Criteria andMailAddressEqualTo(String value) {
			addCriterion("mail_address =", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotEqualTo(String value) {
			addCriterion("mail_address <>", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThan(String value) {
			addCriterion("mail_address >", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
			addCriterion("mail_address >=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThan(String value) {
			addCriterion("mail_address <", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLessThanOrEqualTo(String value) {
			addCriterion("mail_address <=", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressLike(String value) {
			addCriterion("mail_address like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotLike(String value) {
			addCriterion("mail_address not like", value, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressIn(List<String> values) {
			addCriterion("mail_address in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotIn(List<String> values) {
			addCriterion("mail_address not in", values, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressBetween(String value1, String value2) {
			addCriterion("mail_address between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andMailAddressNotBetween(String value1, String value2) {
			addCriterion("mail_address not between", value1, value2, "mailAddress");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIsNull() {
			addCriterion("postal_code is null");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIsNotNull() {
			addCriterion("postal_code is not null");
			return (Criteria) this;
		}

		public Criteria andPostalCodeEqualTo(String value) {
			addCriterion("postal_code =", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotEqualTo(String value) {
			addCriterion("postal_code <>", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeGreaterThan(String value) {
			addCriterion("postal_code >", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
			addCriterion("postal_code >=", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLessThan(String value) {
			addCriterion("postal_code <", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLessThanOrEqualTo(String value) {
			addCriterion("postal_code <=", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLike(String value) {
			addCriterion("postal_code like", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotLike(String value) {
			addCriterion("postal_code not like", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIn(List<String> values) {
			addCriterion("postal_code in", values, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotIn(List<String> values) {
			addCriterion("postal_code not in", values, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeBetween(String value1, String value2) {
			addCriterion("postal_code between", value1, value2, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotBetween(String value1, String value2) {
			addCriterion("postal_code not between", value1, value2, "postalCode");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiIsNull() {
			addCriterion("address_romaji is null");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiIsNotNull() {
			addCriterion("address_romaji is not null");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiEqualTo(String value) {
			addCriterion("address_romaji =", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiNotEqualTo(String value) {
			addCriterion("address_romaji <>", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiGreaterThan(String value) {
			addCriterion("address_romaji >", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiGreaterThanOrEqualTo(String value) {
			addCriterion("address_romaji >=", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiLessThan(String value) {
			addCriterion("address_romaji <", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiLessThanOrEqualTo(String value) {
			addCriterion("address_romaji <=", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiLike(String value) {
			addCriterion("address_romaji like", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiNotLike(String value) {
			addCriterion("address_romaji not like", value, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiIn(List<String> values) {
			addCriterion("address_romaji in", values, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiNotIn(List<String> values) {
			addCriterion("address_romaji not in", values, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiBetween(String value1, String value2) {
			addCriterion("address_romaji between", value1, value2, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andAddressRomajiNotBetween(String value1, String value2) {
			addCriterion("address_romaji not between", value1, value2, "addressRomaji");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNull() {
			addCriterion("birth_date is null");
			return (Criteria) this;
		}

		public Criteria andBirthDateIsNotNull() {
			addCriterion("birth_date is not null");
			return (Criteria) this;
		}

		public Criteria andBirthDateEqualTo(String value) {
			addCriterion("birth_date =", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotEqualTo(String value) {
			addCriterion("birth_date <>", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThan(String value) {
			addCriterion("birth_date >", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateGreaterThanOrEqualTo(String value) {
			addCriterion("birth_date >=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThan(String value) {
			addCriterion("birth_date <", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLessThanOrEqualTo(String value) {
			addCriterion("birth_date <=", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateLike(String value) {
			addCriterion("birth_date like", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotLike(String value) {
			addCriterion("birth_date not like", value, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateIn(List<String> values) {
			addCriterion("birth_date in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotIn(List<String> values) {
			addCriterion("birth_date not in", values, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateBetween(String value1, String value2) {
			addCriterion("birth_date between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andBirthDateNotBetween(String value1, String value2) {
			addCriterion("birth_date not between", value1, value2, "birthDate");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(String value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(String value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(String value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(String value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(String value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(String value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLike(String value) {
			addCriterion("age like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotLike(String value) {
			addCriterion("age not like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<String> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<String> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(String value1, String value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(String value1, String value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(String value) {
			addCriterion("sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(String value) {
			addCriterion("sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(String value) {
			addCriterion("sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(String value) {
			addCriterion("sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(String value) {
			addCriterion("sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(String value) {
			addCriterion("sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLike(String value) {
			addCriterion("sex like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotLike(String value) {
			addCriterion("sex not like", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<String> values) {
			addCriterion("sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<String> values) {
			addCriterion("sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(String value1, String value2) {
			addCriterion("sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(String value1, String value2) {
			addCriterion("sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("phone_number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("phone_number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("phone_number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("phone_number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("phone_number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("phone_number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("phone_number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("phone_number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("phone_number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("phone_number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("phone_number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("phone_number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("phone_number not between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIsNull() {
			addCriterion("cellphone_number is null");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIsNotNull() {
			addCriterion("cellphone_number is not null");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberEqualTo(String value) {
			addCriterion("cellphone_number =", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotEqualTo(String value) {
			addCriterion("cellphone_number <>", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberGreaterThan(String value) {
			addCriterion("cellphone_number >", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("cellphone_number >=", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLessThan(String value) {
			addCriterion("cellphone_number <", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLessThanOrEqualTo(String value) {
			addCriterion("cellphone_number <=", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberLike(String value) {
			addCriterion("cellphone_number like", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotLike(String value) {
			addCriterion("cellphone_number not like", value, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberIn(List<String> values) {
			addCriterion("cellphone_number in", values, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotIn(List<String> values) {
			addCriterion("cellphone_number not in", values, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberBetween(String value1, String value2) {
			addCriterion("cellphone_number between", value1, value2, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andCellphoneNumberNotBetween(String value1, String value2) {
			addCriterion("cellphone_number not between", value1, value2, "cellphoneNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberIsNull() {
			addCriterion("fax_number is null");
			return (Criteria) this;
		}

		public Criteria andFaxNumberIsNotNull() {
			addCriterion("fax_number is not null");
			return (Criteria) this;
		}

		public Criteria andFaxNumberEqualTo(String value) {
			addCriterion("fax_number =", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberNotEqualTo(String value) {
			addCriterion("fax_number <>", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberGreaterThan(String value) {
			addCriterion("fax_number >", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberGreaterThanOrEqualTo(String value) {
			addCriterion("fax_number >=", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberLessThan(String value) {
			addCriterion("fax_number <", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberLessThanOrEqualTo(String value) {
			addCriterion("fax_number <=", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberLike(String value) {
			addCriterion("fax_number like", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberNotLike(String value) {
			addCriterion("fax_number not like", value, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberIn(List<String> values) {
			addCriterion("fax_number in", values, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberNotIn(List<String> values) {
			addCriterion("fax_number not in", values, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberBetween(String value1, String value2) {
			addCriterion("fax_number between", value1, value2, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andFaxNumberNotBetween(String value1, String value2) {
			addCriterion("fax_number not between", value1, value2, "faxNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberIsNull() {
			addCriterion("reg_user_mng_number is null");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberIsNotNull() {
			addCriterion("reg_user_mng_number is not null");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberEqualTo(String value) {
			addCriterion("reg_user_mng_number =", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberNotEqualTo(String value) {
			addCriterion("reg_user_mng_number <>", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberGreaterThan(String value) {
			addCriterion("reg_user_mng_number >", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberGreaterThanOrEqualTo(String value) {
			addCriterion("reg_user_mng_number >=", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberLessThan(String value) {
			addCriterion("reg_user_mng_number <", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberLessThanOrEqualTo(String value) {
			addCriterion("reg_user_mng_number <=", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberLike(String value) {
			addCriterion("reg_user_mng_number like", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberNotLike(String value) {
			addCriterion("reg_user_mng_number not like", value, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberIn(List<String> values) {
			addCriterion("reg_user_mng_number in", values, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberNotIn(List<String> values) {
			addCriterion("reg_user_mng_number not in", values, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberBetween(String value1, String value2) {
			addCriterion("reg_user_mng_number between", value1, value2, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegUserMngNumberNotBetween(String value1, String value2) {
			addCriterion("reg_user_mng_number not between", value1, value2, "regUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("reg_date is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(Date value) {
			addCriterion("reg_date =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(Date value) {
			addCriterion("reg_date <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(Date value) {
			addCriterion("reg_date >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_date >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(Date value) {
			addCriterion("reg_date <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(Date value) {
			addCriterion("reg_date <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<Date> values) {
			addCriterion("reg_date in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<Date> values) {
			addCriterion("reg_date not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(Date value1, Date value2) {
			addCriterion("reg_date between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(Date value1, Date value2) {
			addCriterion("reg_date not between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdIsNull() {
			addCriterion("reg_func_ID is null");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdIsNotNull() {
			addCriterion("reg_func_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdEqualTo(String value) {
			addCriterion("reg_func_ID =", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdNotEqualTo(String value) {
			addCriterion("reg_func_ID <>", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdGreaterThan(String value) {
			addCriterion("reg_func_ID >", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdGreaterThanOrEqualTo(String value) {
			addCriterion("reg_func_ID >=", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdLessThan(String value) {
			addCriterion("reg_func_ID <", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdLessThanOrEqualTo(String value) {
			addCriterion("reg_func_ID <=", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdLike(String value) {
			addCriterion("reg_func_ID like", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdNotLike(String value) {
			addCriterion("reg_func_ID not like", value, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdIn(List<String> values) {
			addCriterion("reg_func_ID in", values, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdNotIn(List<String> values) {
			addCriterion("reg_func_ID not in", values, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdBetween(String value1, String value2) {
			addCriterion("reg_func_ID between", value1, value2, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andRegFuncIdNotBetween(String value1, String value2) {
			addCriterion("reg_func_ID not between", value1, value2, "regFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberIsNull() {
			addCriterion("update_user_mng_number is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberIsNotNull() {
			addCriterion("update_user_mng_number is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberEqualTo(String value) {
			addCriterion("update_user_mng_number =", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberNotEqualTo(String value) {
			addCriterion("update_user_mng_number <>", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberGreaterThan(String value) {
			addCriterion("update_user_mng_number >", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberGreaterThanOrEqualTo(String value) {
			addCriterion("update_user_mng_number >=", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberLessThan(String value) {
			addCriterion("update_user_mng_number <", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberLessThanOrEqualTo(String value) {
			addCriterion("update_user_mng_number <=", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberLike(String value) {
			addCriterion("update_user_mng_number like", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberNotLike(String value) {
			addCriterion("update_user_mng_number not like", value, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberIn(List<String> values) {
			addCriterion("update_user_mng_number in", values, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberNotIn(List<String> values) {
			addCriterion("update_user_mng_number not in", values, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberBetween(String value1, String value2) {
			addCriterion("update_user_mng_number between", value1, value2, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateUserMngNumberNotBetween(String value1, String value2) {
			addCriterion("update_user_mng_number not between", value1, value2, "updateUserMngNumber");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdIsNull() {
			addCriterion("update_func_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdIsNotNull() {
			addCriterion("update_func_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdEqualTo(String value) {
			addCriterion("update_func_ID =", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdNotEqualTo(String value) {
			addCriterion("update_func_ID <>", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdGreaterThan(String value) {
			addCriterion("update_func_ID >", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdGreaterThanOrEqualTo(String value) {
			addCriterion("update_func_ID >=", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdLessThan(String value) {
			addCriterion("update_func_ID <", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdLessThanOrEqualTo(String value) {
			addCriterion("update_func_ID <=", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdLike(String value) {
			addCriterion("update_func_ID like", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdNotLike(String value) {
			addCriterion("update_func_ID not like", value, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdIn(List<String> values) {
			addCriterion("update_func_ID in", values, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdNotIn(List<String> values) {
			addCriterion("update_func_ID not in", values, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdBetween(String value1, String value2) {
			addCriterion("update_func_ID between", value1, value2, "updateFuncId");
			return (Criteria) this;
		}

		public Criteria andUpdateFuncIdNotBetween(String value1, String value2) {
			addCriterion("update_func_ID not between", value1, value2, "updateFuncId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}