package com.sample.gradle.springbatch.common.entity;

import java.io.Serializable;

public class Users implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.age
	 * @mbg.generated
	 */
	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.birthday
	 * @mbg.generated
	 */
	private String birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.tell
	 * @mbg.generated
	 */
	private String tell;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.flag
	 * @mbg.generated
	 */
	private String flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.key1
	 * @mbg.generated
	 */
	private String key1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.key2
	 * @mbg.generated
	 */
	private String key2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.key3
	 * @mbg.generated
	 */
	private String key3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.year
	 * @mbg.generated
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.age
	 * @return  the value of users.age
	 * @mbg.generated
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.age
	 * @param age  the value for users.age
	 * @mbg.generated
	 */
	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.birthday
	 * @return  the value of users.birthday
	 * @mbg.generated
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.birthday
	 * @param birthday  the value for users.birthday
	 * @mbg.generated
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.tell
	 * @return  the value of users.tell
	 * @mbg.generated
	 */
	public String getTell() {
		return tell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.tell
	 * @param tell  the value for users.tell
	 * @mbg.generated
	 */
	public void setTell(String tell) {
		this.tell = tell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.flag
	 * @return  the value of users.flag
	 * @mbg.generated
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.flag
	 * @param flag  the value for users.flag
	 * @mbg.generated
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.key1
	 * @return  the value of users.key1
	 * @mbg.generated
	 */
	public String getKey1() {
		return key1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.key1
	 * @param key1  the value for users.key1
	 * @mbg.generated
	 */
	public void setKey1(String key1) {
		this.key1 = key1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.key2
	 * @return  the value of users.key2
	 * @mbg.generated
	 */
	public String getKey2() {
		return key2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.key2
	 * @param key2  the value for users.key2
	 * @mbg.generated
	 */
	public void setKey2(String key2) {
		this.key2 = key2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.key3
	 * @return  the value of users.key3
	 * @mbg.generated
	 */
	public String getKey3() {
		return key3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.key3
	 * @param key3  the value for users.key3
	 * @mbg.generated
	 */
	public void setKey3(String key3) {
		this.key3 = key3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.year
	 * @return  the value of users.year
	 * @mbg.generated
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.year
	 * @param year  the value for users.year
	 * @mbg.generated
	 */
	public void setYear(String year) {
		this.year = year;
	}
}