package com.sample.gradle.springbatch.common.entity;

import java.util.ArrayList;
import java.util.List;

public class UsersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public UsersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAgeIsNull() {
			addCriterion("age is null");
			return (Criteria) this;
		}

		public Criteria andAgeIsNotNull() {
			addCriterion("age is not null");
			return (Criteria) this;
		}

		public Criteria andAgeEqualTo(String value) {
			addCriterion("age =", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotEqualTo(String value) {
			addCriterion("age <>", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThan(String value) {
			addCriterion("age >", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeGreaterThanOrEqualTo(String value) {
			addCriterion("age >=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThan(String value) {
			addCriterion("age <", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLessThanOrEqualTo(String value) {
			addCriterion("age <=", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeLike(String value) {
			addCriterion("age like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotLike(String value) {
			addCriterion("age not like", value, "age");
			return (Criteria) this;
		}

		public Criteria andAgeIn(List<String> values) {
			addCriterion("age in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotIn(List<String> values) {
			addCriterion("age not in", values, "age");
			return (Criteria) this;
		}

		public Criteria andAgeBetween(String value1, String value2) {
			addCriterion("age between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andAgeNotBetween(String value1, String value2) {
			addCriterion("age not between", value1, value2, "age");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(String value) {
			addCriterion("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(String value) {
			addCriterion("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(String value) {
			addCriterion("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
			addCriterion("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(String value) {
			addCriterion("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(String value) {
			addCriterion("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLike(String value) {
			addCriterion("birthday like", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotLike(String value) {
			addCriterion("birthday not like", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<String> values) {
			addCriterion("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<String> values) {
			addCriterion("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(String value1, String value2) {
			addCriterion("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(String value1, String value2) {
			addCriterion("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andTellIsNull() {
			addCriterion("tell is null");
			return (Criteria) this;
		}

		public Criteria andTellIsNotNull() {
			addCriterion("tell is not null");
			return (Criteria) this;
		}

		public Criteria andTellEqualTo(String value) {
			addCriterion("tell =", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellNotEqualTo(String value) {
			addCriterion("tell <>", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellGreaterThan(String value) {
			addCriterion("tell >", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellGreaterThanOrEqualTo(String value) {
			addCriterion("tell >=", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellLessThan(String value) {
			addCriterion("tell <", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellLessThanOrEqualTo(String value) {
			addCriterion("tell <=", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellLike(String value) {
			addCriterion("tell like", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellNotLike(String value) {
			addCriterion("tell not like", value, "tell");
			return (Criteria) this;
		}

		public Criteria andTellIn(List<String> values) {
			addCriterion("tell in", values, "tell");
			return (Criteria) this;
		}

		public Criteria andTellNotIn(List<String> values) {
			addCriterion("tell not in", values, "tell");
			return (Criteria) this;
		}

		public Criteria andTellBetween(String value1, String value2) {
			addCriterion("tell between", value1, value2, "tell");
			return (Criteria) this;
		}

		public Criteria andTellNotBetween(String value1, String value2) {
			addCriterion("tell not between", value1, value2, "tell");
			return (Criteria) this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("flag is null");
			return (Criteria) this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("flag is not null");
			return (Criteria) this;
		}

		public Criteria andFlagEqualTo(String value) {
			addCriterion("flag =", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotEqualTo(String value) {
			addCriterion("flag <>", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThan(String value) {
			addCriterion("flag >", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(String value) {
			addCriterion("flag >=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThan(String value) {
			addCriterion("flag <", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLessThanOrEqualTo(String value) {
			addCriterion("flag <=", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagLike(String value) {
			addCriterion("flag like", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotLike(String value) {
			addCriterion("flag not like", value, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagIn(List<String> values) {
			addCriterion("flag in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotIn(List<String> values) {
			addCriterion("flag not in", values, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagBetween(String value1, String value2) {
			addCriterion("flag between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andFlagNotBetween(String value1, String value2) {
			addCriterion("flag not between", value1, value2, "flag");
			return (Criteria) this;
		}

		public Criteria andKey1IsNull() {
			addCriterion("key1 is null");
			return (Criteria) this;
		}

		public Criteria andKey1IsNotNull() {
			addCriterion("key1 is not null");
			return (Criteria) this;
		}

		public Criteria andKey1EqualTo(String value) {
			addCriterion("key1 =", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1NotEqualTo(String value) {
			addCriterion("key1 <>", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1GreaterThan(String value) {
			addCriterion("key1 >", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1GreaterThanOrEqualTo(String value) {
			addCriterion("key1 >=", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1LessThan(String value) {
			addCriterion("key1 <", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1LessThanOrEqualTo(String value) {
			addCriterion("key1 <=", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1Like(String value) {
			addCriterion("key1 like", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1NotLike(String value) {
			addCriterion("key1 not like", value, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1In(List<String> values) {
			addCriterion("key1 in", values, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1NotIn(List<String> values) {
			addCriterion("key1 not in", values, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1Between(String value1, String value2) {
			addCriterion("key1 between", value1, value2, "key1");
			return (Criteria) this;
		}

		public Criteria andKey1NotBetween(String value1, String value2) {
			addCriterion("key1 not between", value1, value2, "key1");
			return (Criteria) this;
		}

		public Criteria andKey2IsNull() {
			addCriterion("key2 is null");
			return (Criteria) this;
		}

		public Criteria andKey2IsNotNull() {
			addCriterion("key2 is not null");
			return (Criteria) this;
		}

		public Criteria andKey2EqualTo(String value) {
			addCriterion("key2 =", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2NotEqualTo(String value) {
			addCriterion("key2 <>", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2GreaterThan(String value) {
			addCriterion("key2 >", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2GreaterThanOrEqualTo(String value) {
			addCriterion("key2 >=", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2LessThan(String value) {
			addCriterion("key2 <", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2LessThanOrEqualTo(String value) {
			addCriterion("key2 <=", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2Like(String value) {
			addCriterion("key2 like", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2NotLike(String value) {
			addCriterion("key2 not like", value, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2In(List<String> values) {
			addCriterion("key2 in", values, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2NotIn(List<String> values) {
			addCriterion("key2 not in", values, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2Between(String value1, String value2) {
			addCriterion("key2 between", value1, value2, "key2");
			return (Criteria) this;
		}

		public Criteria andKey2NotBetween(String value1, String value2) {
			addCriterion("key2 not between", value1, value2, "key2");
			return (Criteria) this;
		}

		public Criteria andKey3IsNull() {
			addCriterion("key3 is null");
			return (Criteria) this;
		}

		public Criteria andKey3IsNotNull() {
			addCriterion("key3 is not null");
			return (Criteria) this;
		}

		public Criteria andKey3EqualTo(String value) {
			addCriterion("key3 =", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3NotEqualTo(String value) {
			addCriterion("key3 <>", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3GreaterThan(String value) {
			addCriterion("key3 >", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3GreaterThanOrEqualTo(String value) {
			addCriterion("key3 >=", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3LessThan(String value) {
			addCriterion("key3 <", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3LessThanOrEqualTo(String value) {
			addCriterion("key3 <=", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3Like(String value) {
			addCriterion("key3 like", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3NotLike(String value) {
			addCriterion("key3 not like", value, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3In(List<String> values) {
			addCriterion("key3 in", values, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3NotIn(List<String> values) {
			addCriterion("key3 not in", values, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3Between(String value1, String value2) {
			addCriterion("key3 between", value1, value2, "key3");
			return (Criteria) this;
		}

		public Criteria andKey3NotBetween(String value1, String value2) {
			addCriterion("key3 not between", value1, value2, "key3");
			return (Criteria) this;
		}

		public Criteria andYearIsNull() {
			addCriterion("year is null");
			return (Criteria) this;
		}

		public Criteria andYearIsNotNull() {
			addCriterion("year is not null");
			return (Criteria) this;
		}

		public Criteria andYearEqualTo(String value) {
			addCriterion("year =", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotEqualTo(String value) {
			addCriterion("year <>", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearGreaterThan(String value) {
			addCriterion("year >", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearGreaterThanOrEqualTo(String value) {
			addCriterion("year >=", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLessThan(String value) {
			addCriterion("year <", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLessThanOrEqualTo(String value) {
			addCriterion("year <=", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLike(String value) {
			addCriterion("year like", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotLike(String value) {
			addCriterion("year not like", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearIn(List<String> values) {
			addCriterion("year in", values, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotIn(List<String> values) {
			addCriterion("year not in", values, "year");
			return (Criteria) this;
		}

		public Criteria andYearBetween(String value1, String value2) {
			addCriterion("year between", value1, value2, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotBetween(String value1, String value2) {
			addCriterion("year not between", value1, value2, "year");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table users
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 20 21:58:50 JST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}