package com.sample.gradle.springbatch.common.mapper;

import com.sample.gradle.springbatch.common.entity.HUserInfo;
import com.sample.gradle.springbatch.common.entity.HUserInfoExample;
import com.sample.gradle.springbatch.common.entity.HUserInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HUserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	long countByExample(HUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int deleteByExample(HUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(HUserInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int insert(HUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int insertSelective(HUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	List<HUserInfo> selectByExample(HUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	HUserInfo selectByPrimaryKey(HUserInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") HUserInfo record, @Param("example") HUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") HUserInfo record, @Param("example") HUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(HUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table h_user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(HUserInfo record);
}