package com.sample.gradle.springbatch.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sample.gradle.springbatch.common.entity.TUserInfo;
import com.sample.gradle.springbatch.common.entity.TUserInfoExample;

public interface TUserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	long countByExample(TUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int deleteByExample(TUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String userMngNumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int insert(TUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int insertSelective(TUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	List<TUserInfo> selectByExample(TUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	TUserInfo selectByPrimaryKey(String userMngNumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TUserInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TUserInfo record);
}